### ISSUE TITLE
flax-community/dansk-gpt-wiki could not be benchmarked on the truncated version of AngryTweets

### ISSUE THREAD

**Issue by peter-sk** [saattrupdan/ScandEval#52]
The error message was:
The vocab size of the tokenizer is larger than the vocab size of the model. This is not supported.

This is a pretty standard situation for GPT-style models. I am training another large model, where the same issue occurs.

**Comment by saattrupdan** [comment]
Hi @peter-sk. 

The reason I introduced that error is because the tokeniser would use some of the token ids not covered by the embedding layer, leading to an IndexError. 

If it is indeed normal, would I be able to simply remove those extra token ids from the tokeniser to avoid that error, or do you need them for something during training or inference?

**Comment by peter-sk** [comment]
A pull request has been made. I found an obvious omission when testing and added a second commit. Please have a look. Feedback is welcome.

**Comment by peter-sk** [comment]
Taken care of by #53.
